### ISSUE TITLE
adding to report analysis

### ISSUE THREAD

**Issue by bettybhzhou** [UBC-MDS/San_Francisco_Crime_Resolution_Model#15]
Hi Ian,

 I took another look at the report. I was wondering if you could add that we optimized for the max_depth and min_sample_split and also, that we balanced the classifier to the analysis? (based on the code below)
```
parameters ={'max_depth': np.arange(1, 30, 5), 
             'min_samples_split': np.arange(2, 400, 20)}

tree = DecisionTreeClassifier(class_weight='balanced')
clf = GridSearchCV(tree, parameters, cv = 10)
clf.fit(X_train, y_train)
```
I missed it last time, but I think it's important to specify in our analysis.

Thank you, 
Betty

**Comment by ian-flores** [comment]
I lost track of the commit, but it has been addressed.
