### ISSUE TITLE
Feedback from Peer Review

### ISSUE THREAD

**Issue by bettybhzhou** [UBC-MDS/San_Francisco_Crime_Resolution_Model#16]
These are the suggestions provided by peers on our project:

1) Convert the feature importance table to a bar graph to provide better visualization and summary of results.

2) Include details about analysis such as the hyperparameters used for building the classifier (i.e. k for cross-validation, min_sample_split value, max_depth used).

3) Add to future direction about how our decision tree classifier would compare to a Naive Bayes classifier.

**Comment by ian-flores** [comment]
Hi @bettybhzhou in PR #18 I added the bar graph to visualize the feature importances.
