### ISSUE TITLE
Add a tiny bit more detail to your usage instructions 

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/San_Francisco_Crime_Resolution_Model#22]
I think its always helpful to be extra clear in the usage instructions, so I would suggest that you indicate all the commands you suggest are expected to be run from the root of this project.

**Comment by bettybhzhou** [comment]
Hi Tiffany, 

we've included all the commands that are expected to be run from the root in the README.md as shown below. I'm unsure of what additional details are needed. Further suggestions would be much appreciated. Thank you!

```bash
python src/01_clean_data.py 1000 data/san_francisco_clean.csv
python src/02_EDA.py data/san_francisco_clean.csv results/figures/
python src/03_feature_engineering.py data/san_francisco_clean.csv data/san_francisco_features.csv
python src/04_decison_tree.py data/san_francisco_features.csv data/feature_results.csv
Rscript src/03_Exploratory_SF_map.R data/san_francisco_clean.csv results/figures/
Rscript -e "rmarkdown::render('docs/san_francisco_report.Rmd')"
```
Or, run all scripts using the following command:

```bash
make all
```

**Comment by ian-flores** [comment]
I lost track of the commit, but it is now addressed in the README.
