### ISSUE TITLE
Dependency versions of R & Python needed

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/San_Francisco_Crime_Resolution_Model#23]
Please add the dependency versions R & Python in the dependencies section.

**Comment by ian-flores** [comment]
@ttimbers what do you mean by add the dependency versions? They are available in the [README](https://github.com/UBC-MDS/San_Francisco_Crime_Resolution_Model/blob/master/README.md#dependencies) under the dependencies section. Do we need to list them somewhere else?

**Comment by ttimbers** [comment]
There is no version listed for R there. And it says Python 3, but was it Python 3.5? 3.7?

**Comment by ian-flores** [comment]
Oh okay, I misunderstood, apologies. I thought it was for the packages. I'll add them. Thanks Tiffany!
