### ISSUE TITLE
Analysis Pipeline Distribution of tasks

### ISSUE THREAD

**Issue by ian-flores** [UBC-MDS/San_Francisco_Crime_Resolution_Model#5]
Hi @bettybhzhou, how do you think we can divide the work for the pipeline?

**Comment by bettybhzhou** [comment]
Sure, sounds good. How would you like to split up the work?

**Comment by ian-flores** [comment]
I can do the re-coding of the target variable, and some EDA today, and we can discuss the ML part tomorrow at lab.

**Comment by ian-flores** [comment]
As we talked today we can divide the work the following way: 

Betty:
- Plots of the EDA
    - Script 2

Ian:
- Pre-processing of the features
   - Script 3

Together:
- Machine Learning Script

**Comment by ian-flores** [comment]
Betty:

- Make the EDA plots
- Make the map plot

Ian:

- Loading data script (needs cleaning)
- Cleaning data script (needs cleaning)
- Feature Engineering (needs cleaning)

Together:

- Machine Learning Model and Optimization (needs cleaning)

Report:

- Introduction (Ian)
    - Question
    - Justification
    - The dataset
    
- Findings and results (Ian)
    - Present & Interpret
    
- Critiquing the analyses (Betty)
    - Limitations & Assumptions, etc
    
- Future Direction (Betty)

- References (Together)

README.md

- Summary (Betty)
- Execution Order and Dependencies (Ian)
