### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/San_Francisco_Crime_Resolution_Model#6]
__Mechanics__

* The link in your proposal repo only redirect to the release page of the project repo. You can also create a direct link to v1.0 of the repo with https://github.com/UBC-MDS/DSCI_522_SF_crime/tree/v0.1.

* Would be nice to show in README that the data importing script does run and maybe print the first few rows of the data.

__Reasoning__

* Maybe this wasn’t covered at the time of writing your proposal, you might want to mention how you are going to train and tune your decision tree in terms of tuning and transformation of the predictions, in addition to what packages you will use. Since a good portion of the predictors are categorical, are you going to use all classes as is? Maybe some classes for these predictors will be quite rare as well?

__Other comments__

* Might be interesting to plot the incidents on a map of SF as part of an initial data exploration. With 2 million data points the map might look very busy though, might need to subsample or make a heat map instead.

**Comment by bettybhzhou** [comment]
PR [#18](https://github.com/UBC-MDS/San_Francisco_Crime_Resolution_Model/pull/18) addresses all the following issues:
1) Data importing and evidence in README
2) Reasoning issues above in 4.0 Analysis Workflow of [final report](https://github.com/UBC-MDS/San_Francisco_Crime_Resolution_Model/blob/master/docs/san_francisco_report.md#analysis-workflow).
3) Plot of incidents on a map of SF in 3.0 Exploratory Data Analysis section of [final report](https://github.com/UBC-MDS/San_Francisco_Crime_Resolution_Model/blob/master/docs/san_francisco_report.md#analysis-workflow).
